-- PostgreSQL Schema Backup
-- Database: default
-- Host: 127.0.0.1:5432
-- Generated by psql-watcher script.sh

-- ==============================================
-- SCHEMA BACKUP FOR DATABASE: default
-- ==============================================

--
-- PostgreSQL database dump
--

\restrict 7DSh3E2TiHIVq6nhVAw3YFPfqdnFTFDSepaFEuWQVcmoVx8UTgqKe8MdDPilhBX

-- Dumped from database version 13.22 (Debian 13.22-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_table_access_method = heap;

--
-- Name: migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    applied_at timestamp without time zone NOT NULL
);


--
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- Name: test_table; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_table (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(255),
    age integer,
    is_active boolean NOT NULL,
    status character varying(50),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: test_table_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.test_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: test_table_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.test_table_id_seq OWNED BY public.test_table.id;


--
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- Name: test_table id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_table ALTER COLUMN id SET DEFAULT nextval('public.test_table_id_seq'::regclass);


--
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- Name: test_table test_table_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_table
    ADD CONSTRAINT test_table_pkey PRIMARY KEY (id);


--
-- Name: migration_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX migration_name ON public.migrations USING btree (name);


--
-- PostgreSQL database dump complete
--

\unrestrict 7DSh3E2TiHIVq6nhVAw3YFPfqdnFTFDSepaFEuWQVcmoVx8UTgqKe8MdDPilhBX

 CREATE ROLE pg_execute_server_program;
 CREATE ROLE pg_monitor;
 CREATE ROLE pg_read_all_settings;
 CREATE ROLE pg_read_all_stats;
 CREATE ROLE pg_read_server_files;
 CREATE ROLE pg_signal_backend;
 CREATE ROLE pg_stat_scan_tables;
 CREATE ROLE pg_write_server_files;

 GRANT SELECT ON administrable_role_authorizations TO PUBLIC;
 GRANT SELECT ON applicable_roles TO PUBLIC;
 GRANT SELECT ON attributes TO PUBLIC;
 GRANT SELECT ON character_sets TO PUBLIC;
 GRANT SELECT ON check_constraint_routine_usage TO PUBLIC;
 GRANT SELECT ON check_constraints TO PUBLIC;
 GRANT SELECT ON collation_character_set_applicability TO PUBLIC;
 GRANT SELECT ON collations TO PUBLIC;
 GRANT SELECT ON column_column_usage TO PUBLIC;
 GRANT SELECT ON column_domain_usage TO PUBLIC;
 GRANT SELECT ON column_options TO PUBLIC;
 GRANT SELECT ON column_privileges TO PUBLIC;
 GRANT SELECT ON column_udt_usage TO PUBLIC;
 GRANT SELECT ON columns TO PUBLIC;
 GRANT SELECT ON constraint_column_usage TO PUBLIC;
 GRANT SELECT ON constraint_table_usage TO PUBLIC;
 GRANT SELECT ON data_type_privileges TO PUBLIC;
 GRANT SELECT ON domain_constraints TO PUBLIC;
 GRANT SELECT ON domain_udt_usage TO PUBLIC;
 GRANT SELECT ON domains TO PUBLIC;
 GRANT SELECT ON element_types TO PUBLIC;
 GRANT SELECT ON enabled_roles TO PUBLIC;
 GRANT SELECT ON foreign_data_wrapper_options TO PUBLIC;
 GRANT SELECT ON foreign_data_wrappers TO PUBLIC;
 GRANT SELECT ON foreign_server_options TO PUBLIC;
 GRANT SELECT ON foreign_servers TO PUBLIC;
 GRANT SELECT ON foreign_table_options TO PUBLIC;
 GRANT SELECT ON foreign_tables TO PUBLIC;
 GRANT SELECT ON information_schema_catalog_name TO PUBLIC;
 GRANT SELECT ON key_column_usage TO PUBLIC;
 GRANT SELECT ON parameters TO PUBLIC;
 GRANT SELECT ON pg_aggregate TO PUBLIC;
 GRANT SELECT ON pg_am TO PUBLIC;
 GRANT SELECT ON pg_amop TO PUBLIC;
 GRANT SELECT ON pg_amproc TO PUBLIC;
 GRANT SELECT ON pg_attrdef TO PUBLIC;
 GRANT SELECT ON pg_attribute TO PUBLIC;
 GRANT SELECT ON pg_auth_members TO PUBLIC;
 GRANT SELECT ON pg_available_extension_versions TO PUBLIC;
 GRANT SELECT ON pg_available_extensions TO PUBLIC;
 GRANT SELECT ON pg_cast TO PUBLIC;
 GRANT SELECT ON pg_class TO PUBLIC;
 GRANT SELECT ON pg_collation TO PUBLIC;
 GRANT SELECT ON pg_constraint TO PUBLIC;
 GRANT SELECT ON pg_conversion TO PUBLIC;
 GRANT SELECT ON pg_cursors TO PUBLIC;
 GRANT SELECT ON pg_database TO PUBLIC;
 GRANT SELECT ON pg_db_role_setting TO PUBLIC;
 GRANT SELECT ON pg_default_acl TO PUBLIC;
 GRANT SELECT ON pg_depend TO PUBLIC;
 GRANT SELECT ON pg_description TO PUBLIC;
 GRANT SELECT ON pg_enum TO PUBLIC;
 GRANT SELECT ON pg_event_trigger TO PUBLIC;
 GRANT SELECT ON pg_extension TO PUBLIC;
 GRANT SELECT ON pg_foreign_data_wrapper TO PUBLIC;
 GRANT SELECT ON pg_foreign_server TO PUBLIC;
 GRANT SELECT ON pg_foreign_table TO PUBLIC;
 GRANT SELECT ON pg_group TO PUBLIC;
 GRANT SELECT ON pg_index TO PUBLIC;
 GRANT SELECT ON pg_indexes TO PUBLIC;
 GRANT SELECT ON pg_inherits TO PUBLIC;
 GRANT SELECT ON pg_init_privs TO PUBLIC;
 GRANT SELECT ON pg_language TO PUBLIC;
 GRANT SELECT ON pg_largeobject_metadata TO PUBLIC;
 GRANT SELECT ON pg_locks TO PUBLIC;
 GRANT SELECT ON pg_matviews TO PUBLIC;
 GRANT SELECT ON pg_namespace TO PUBLIC;
 GRANT SELECT ON pg_opclass TO PUBLIC;
 GRANT SELECT ON pg_operator TO PUBLIC;
 GRANT SELECT ON pg_opfamily TO PUBLIC;
 GRANT SELECT ON pg_partitioned_table TO PUBLIC;
 GRANT SELECT ON pg_policies TO PUBLIC;
 GRANT SELECT ON pg_policy TO PUBLIC;
 GRANT SELECT ON pg_prepared_statements TO PUBLIC;
 GRANT SELECT ON pg_prepared_xacts TO PUBLIC;
 GRANT SELECT ON pg_proc TO PUBLIC;
 GRANT SELECT ON pg_publication TO PUBLIC;
 GRANT SELECT ON pg_publication_rel TO PUBLIC;
 GRANT SELECT ON pg_publication_tables TO PUBLIC;
 GRANT SELECT ON pg_range TO PUBLIC;
 GRANT SELECT ON pg_replication_origin TO PUBLIC;
 GRANT SELECT ON pg_replication_slots TO PUBLIC;
 GRANT SELECT ON pg_rewrite TO PUBLIC;
 GRANT SELECT ON pg_roles TO PUBLIC;
 GRANT SELECT ON pg_rules TO PUBLIC;
 GRANT SELECT ON pg_seclabel TO PUBLIC;
 GRANT SELECT ON pg_seclabels TO PUBLIC;
 GRANT SELECT ON pg_sequence TO PUBLIC;
 GRANT SELECT ON pg_sequences TO PUBLIC;
 GRANT SELECT ON pg_settings TO PUBLIC;
 GRANT UPDATE ON pg_settings TO PUBLIC;
 GRANT SELECT ON pg_shdepend TO PUBLIC;
 GRANT SELECT ON pg_shdescription TO PUBLIC;
 GRANT SELECT ON pg_shseclabel TO PUBLIC;
 GRANT SELECT ON pg_stat_activity TO PUBLIC;
 GRANT SELECT ON pg_stat_all_indexes TO PUBLIC;
 GRANT SELECT ON pg_stat_all_tables TO PUBLIC;
 GRANT SELECT ON pg_stat_archiver TO PUBLIC;
 GRANT SELECT ON pg_stat_bgwriter TO PUBLIC;
 GRANT SELECT ON pg_stat_database TO PUBLIC;
 GRANT SELECT ON pg_stat_database_conflicts TO PUBLIC;
 GRANT SELECT ON pg_stat_gssapi TO PUBLIC;
 GRANT SELECT ON pg_stat_progress_analyze TO PUBLIC;
 GRANT SELECT ON pg_stat_progress_basebackup TO PUBLIC;
 GRANT SELECT ON pg_stat_progress_cluster TO PUBLIC;
 GRANT SELECT ON pg_stat_progress_create_index TO PUBLIC;
 GRANT SELECT ON pg_stat_progress_vacuum TO PUBLIC;
 GRANT SELECT ON pg_stat_replication TO PUBLIC;
 GRANT SELECT ON pg_stat_slru TO PUBLIC;
 GRANT SELECT ON pg_stat_ssl TO PUBLIC;
 GRANT SELECT ON pg_stat_subscription TO PUBLIC;
 GRANT SELECT ON pg_stat_sys_indexes TO PUBLIC;
 GRANT SELECT ON pg_stat_sys_tables TO PUBLIC;
 GRANT SELECT ON pg_stat_user_functions TO PUBLIC;
 GRANT SELECT ON pg_stat_user_indexes TO PUBLIC;
 GRANT SELECT ON pg_stat_user_tables TO PUBLIC;
 GRANT SELECT ON pg_stat_wal_receiver TO PUBLIC;
 GRANT SELECT ON pg_stat_xact_all_tables TO PUBLIC;
 GRANT SELECT ON pg_stat_xact_sys_tables TO PUBLIC;
 GRANT SELECT ON pg_stat_xact_user_functions TO PUBLIC;
 GRANT SELECT ON pg_stat_xact_user_tables TO PUBLIC;
 GRANT SELECT ON pg_statio_all_indexes TO PUBLIC;
 GRANT SELECT ON pg_statio_all_sequences TO PUBLIC;
 GRANT SELECT ON pg_statio_all_tables TO PUBLIC;
 GRANT SELECT ON pg_statio_sys_indexes TO PUBLIC;
 GRANT SELECT ON pg_statio_sys_sequences TO PUBLIC;
 GRANT SELECT ON pg_statio_sys_tables TO PUBLIC;
 GRANT SELECT ON pg_statio_user_indexes TO PUBLIC;
 GRANT SELECT ON pg_statio_user_sequences TO PUBLIC;
 GRANT SELECT ON pg_statio_user_tables TO PUBLIC;
 GRANT SELECT ON pg_statistic_ext TO PUBLIC;
 GRANT SELECT ON pg_stats TO PUBLIC;
 GRANT SELECT ON pg_stats_ext TO PUBLIC;
 GRANT SELECT ON pg_subscription_rel TO PUBLIC;
 GRANT SELECT ON pg_tables TO PUBLIC;
 GRANT SELECT ON pg_tablespace TO PUBLIC;
 GRANT SELECT ON pg_timezone_abbrevs TO PUBLIC;
 GRANT SELECT ON pg_timezone_names TO PUBLIC;
 GRANT SELECT ON pg_transform TO PUBLIC;
 GRANT SELECT ON pg_trigger TO PUBLIC;
 GRANT SELECT ON pg_ts_config TO PUBLIC;
 GRANT SELECT ON pg_ts_config_map TO PUBLIC;
 GRANT SELECT ON pg_ts_dict TO PUBLIC;
 GRANT SELECT ON pg_ts_parser TO PUBLIC;
 GRANT SELECT ON pg_ts_template TO PUBLIC;
 GRANT SELECT ON pg_type TO PUBLIC;
 GRANT SELECT ON pg_user TO PUBLIC;
 GRANT SELECT ON pg_user_mappings TO PUBLIC;
 GRANT SELECT ON pg_views TO PUBLIC;
 GRANT SELECT ON referential_constraints TO PUBLIC;
 GRANT SELECT ON role_column_grants TO PUBLIC;
 GRANT SELECT ON role_routine_grants TO PUBLIC;
 GRANT SELECT ON role_table_grants TO PUBLIC;
 GRANT SELECT ON role_udt_grants TO PUBLIC;
 GRANT SELECT ON role_usage_grants TO PUBLIC;
 GRANT SELECT ON routine_privileges TO PUBLIC;
 GRANT SELECT ON routines TO PUBLIC;
 GRANT SELECT ON schemata TO PUBLIC;
 GRANT SELECT ON sequences TO PUBLIC;
 GRANT SELECT ON sql_features TO PUBLIC;
 GRANT SELECT ON sql_implementation_info TO PUBLIC;
 GRANT SELECT ON sql_sizing TO PUBLIC;
 GRANT SELECT ON table_constraints TO PUBLIC;
 GRANT SELECT ON table_privileges TO PUBLIC;
 GRANT SELECT ON tables TO PUBLIC;
 GRANT SELECT ON triggered_update_columns TO PUBLIC;
 GRANT SELECT ON triggers TO PUBLIC;
 GRANT SELECT ON udt_privileges TO PUBLIC;
 GRANT SELECT ON usage_privileges TO PUBLIC;
 GRANT SELECT ON user_defined_types TO PUBLIC;
 GRANT SELECT ON user_mapping_options TO PUBLIC;
 GRANT SELECT ON user_mappings TO PUBLIC;
 GRANT SELECT ON view_column_usage TO PUBLIC;
 GRANT SELECT ON view_routine_usage TO PUBLIC;
 GRANT SELECT ON view_table_usage TO PUBLIC;
 GRANT SELECT ON views TO PUBLIC;

CREATE SEQUENCE public.migrations_id_seq
CREATE SEQUENCE public.test_table_id_seq

 ALTER DATABASE default SET application_name = psql;
 ALTER DATABASE default SET config_file = /var/lib/postgresql/data/postgresql.conf;
 ALTER DATABASE default SET data_directory = /var/lib/postgresql/data;
 ALTER DATABASE default SET DateStyle = ISO, MDY;
 ALTER DATABASE default SET default_text_search_config = pg_catalog.english;
 ALTER DATABASE default SET dynamic_shared_memory_type = posix;
 ALTER DATABASE default SET hba_file = /var/lib/postgresql/data/pg_hba.conf;
 ALTER DATABASE default SET ident_file = /var/lib/postgresql/data/pg_ident.conf;
 ALTER DATABASE default SET lc_messages = en_US.utf8;
 ALTER DATABASE default SET lc_monetary = en_US.utf8;
 ALTER DATABASE default SET lc_numeric = en_US.utf8;
 ALTER DATABASE default SET lc_time = en_US.utf8;
 ALTER DATABASE default SET listen_addresses = *;
 ALTER DATABASE default SET max_connections = 100;
 ALTER DATABASE default SET max_stack_depth = 2048;
 ALTER DATABASE default SET shared_buffers = 16384;
 ALTER DATABASE default SET TimeZone = Etc/UTC;
 ALTER DATABASE default SET transaction_deferrable = off;
 ALTER DATABASE default SET transaction_isolation = read committed;
 ALTER DATABASE default SET transaction_read_only = off;
 ALTER DATABASE default SET wal_buffers = 512;


-- ==============================================
-- BACKUP COMPLETED
-- ==============================================
-- Database: default
-- Host: 127.0.0.1:5432
-- ==============================================

